version: "2"
services:
  # Nginx web server
  nginx:
    image: trambar/trambar-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/etc/nginx/extra
      - ${TRAMBAR_MEDIA_FOLDER}:/var/cache/media
      - ${TRAMBAR_SSL_FOLDER}:${TRAMBAR_SSL_FOLDER}
    depends_on:
      - data_server
      - event_notifier
  # PostgreSQL database manager
  postgres:
    image: trambar/trambar-postgres
    volumes:
      - ${TRAMBAR_DATABASE_FOLDER}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ROOT_PASSWORD}
  schema_manager:
    image: trambar/trambar-node
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ROOT_PASSWORD}
      - DATABASE_ADMIN_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
      - DATABASE_CLIENT_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
      - DATABASE_AUTH_PASSWORD=${TRAMBAR_DATABASE_AUTH_PASSWORD}
    command: [ node, schema-manager.js ]
    depends_on:
      - postgres
  # Data server (Node.js)
  data_server:
    image: trambar/trambar-node
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, data-server.js ]
    depends_on:
      - postgres
  # Admin data server (Node.js)
  admin_data_server:
    image: trambar/trambar-node
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=admin_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
    command: [ node, data-server.js ]
    depends_on:
      - postgres
  # Authentication manager (Node.js)
  auth_manager:
    image: trambar/trambar-node
    volumes:
      - ${TRAMBAR_HTPASSWD_FOLDER}:/etc/trambar
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=auth_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_AUTH_PASSWORD}
      - HTPASSWD_PATH=/etc/trambar/${TRAMBAR_HTPASSWD_NAME}
    command: [ node, auth-manager.js ]
    depends_on:
      - postgres
  # Media server (Node.js)
  media_server:
    image: trambar/trambar-node
    volumes:
      - ${TRAMBAR_MEDIA_FOLDER}:/var/cache/media
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, media-server.js ]
    depends_on:
      - postgres
  # WebSocket Notifier (Node.js)
  event_notifier:
    image: trambar/trambar-node
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, event-notifier.js ]
    depends_on:
      - postgres
  # Live Data Invalidator (Node.js)
  live_data_invalidator:
    image: trambar/trambar-node
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, live-data-invalidator.js ]
    depends_on:
      - postgres
  # Live Data Updater (Node.js)
  live_data_updater:
    image: trambar/trambar-node
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, live-data-updater.js ]
    depends_on:
      - postgres
  # GitLab Adapter (Node.js)
  gitlab_adapter:
    image: trambar/trambar-node
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=production
      - HOST_DOMAIN_NAME=${TRAMBAR_DOMAIN_NAME}
      - WEB_SERVER_PROTOCOL=${TRAMBAR_PROTOCOL}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=admin_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
    command: [ node, gitlab-adapter.js ]
    depends_on:
      - postgres
